### ISSUE TITLE
Create a a new issue template for Dev frontend team internal usage

### ISSUE THREAD

**Issue by henrynoowah** [iCloudHospital/.github#13]
- [x] **Draft** 

## Description

- Create a new template which could be used by the @iCloudHospital/front-end 
- Currently the dev dev team members does not have specific template being used internally
- Members use `custom.md` and freely update the template as needed
- This results in some members not managing the issue with detailed information such as below
  - https://github.com/iCloudHospital/cloudhospital.admin/issues/1451
  - https://github.com/iCloudHospital/saas-next/issues/7

## Checklist

- [x] Create a example issue and get reviewed by related memebers
- [ ] Create new issue template `issue-dev-frontend.md`
- [ ] Consider how management method between issue & draft issue will be done
- [ ] Consider naming convention of issues

**Issue template section checklist**
- [ ] Linked Issue
- [ ] Description : Required
- [ ] Checklist
- [ ] Additional Context

## Additional context

 🌟 This issue is the the example template which will be used as base for `issue-dev-frontend.md`

## References

 

- [Wiki - Developers guide](https://github.com/iCloudHospital/iCloudHospital/wiki/Developers-guide#github-projects)

**Comment by henrynoowah** [comment]
## Template draft

```md
---
name: 💻 Fronted dev team internal issue template
about: Internal issue template for Frontend dev team
title: ""
labels: ""
assignees: ""
---

<!--
  Checking this will indicate that the current issue is still draft
-->

- [x] **Draft**

## Linked Issue

<!-- !REQUIRED -->
<!--
  Provide a link to related Issue or Pull requests
  check example for usage reference
  example:
  - #1451
  - https://github.com/iCloudHospital/iCloudHospital/issues/1120
  - [ ] #1451
  - [ ] https://github.com/iCloudHospital/saas-next/issues/7
-->

## Description

<!-- !REQUIRED -->
<!--
  Provide a clear and concise description of what the problem is.
-->

## Checklist

<!--
  If the issue requires multiple steps or multiple tasks Provide a checklist
-->

## Additional context

<!--
  Is there anything else you can add about the proposal?
  You might want to link to related issues here, if you haven't already.
-->

## References

<!--
  Please specify related issues and provide helpful links.
-->

```

**Comment by henrynoowah** [comment]
## Issue naming convention

### Internal (`ICH`, `Admin`, `SaaS`)

`Title` must be descriptive
**example :**
❌ Hospital contacts
✅ Implement hospital contacts management page
✅ Update hospital contacnts form to manage newely updated `ContactType`

**Comment by akagaeng** [comment]
의견

1. Draft 여부는 Description 아래에 넣어두고, draft 가 아닌 경우에는 그냥 내용만 적어두면 어떨까 싶습니다. (Draft 가 아닌 경우에 보기가 좀 거추장스러워보이는것같아요)
2. Linked Issue 도 Reference 위쪽이나 Description 쪽에 옮기면 어떨까요. 개인적으로는 Description이 이슈에서 가장 중요한 것이 아닌가 싶어요

저의 의견을 반영한 템플릿 아래에 넣어볼게요

<br/>

## Description

Draft 이더라도 간단한 내용은 적어두기


- [x] **Draft** => Draft 인 경우에 체크, 향후 이슈 작성 시에는 삭제

### Linked Issues

* 관련 이슈가 있는 경우 (Description 내에 포함 또는 별도 섹션..)

## Checklist

- [ ] A
- [ ] B

## Additional context

...

## Linked Issues

* 관련 이슈가 있는 경우 (Description 내에 포함 또는 별도 섹션..)

## References

* ...

**Comment by henrynoowah** [comment]
@akagaeng 
확인이 늦어 죄송합니다.
.github 레포는 멘션에 대한 알림 설정이 안되어있는지 몰라 이사님 의견을 확인 못하고 PR 머지를 했습니다.
추가 반영 후 새로운 PR을 올리겠습니다!

```markdown
---
name: 💻 Fronted dev team internal issue template
about: Internal issue template for Frontend dev team
title: ""
labels: ""
assignees: ""
---

<!--
  Checking this will indicate that the current issue is still draft
-->

## Description

<!-- !REQUIRED -->
<!--
  Provide a clear and concise description of what the problem is.
  * Check the `Draft` checkbox if the issue is yet to be completed
  * Please do not create empty issue even when issue is marked as `Draft`
-->

- [ ] **Draft**

## Linked Issue

<!--
  Provide a link to related Issue or Pull requests
  check example for usage reference
  example:
  - #1451
  - https://github.com/iCloudHospital/iCloudHospital/issues/1120
  - [ ] #1451
  - [ ] https://github.com/iCloudHospital/saas-next/issues/7
-->

## Checklist

<!--
  If the issue requires multiple steps or multiple tasks Provide a checklist
-->

## Additional context

<!--
  Is there anything else you can add about the proposal?
  You might want to link to related issues here, if you haven't already.
-->

## References

<!--
  Please specify related issues and provide helpful links.
-->

```


---

**Preview**



## Description




- [x] **Draft**
* Description

## Linked Issue



## Checklist



- [ ] Checklist 1
- [ ] Checklist 2

## Additional context



* Additional context

## References



* Reference

**Comment by henrynoowah** [comment]
@akagaeng 
cc: @iCloudHospital/front-end 

템플릿 + 이사님 추가의견 반영한 이슈 예제입니다. 시간나실 때 한 번 확인 부탁드립니다

- https://github.com/iCloudHospital/cloudhospital.admin/issues/1451
