### ISSUE TITLE
Add region section in the `Github` issue template.

### ISSUE THREAD

**Issue by sejune-oh** [iCloudHospital/.github#20]
### Summary
- Currently,  we should set region property when we deploy the SaaS page
- Adding a tag creation request so that new tags can be applied when a requester requests to deploy a SaaS page 

There are new updates to the SaaS deployment process.
Regions have been added for administrators to deploy to.
New tags have also been added to manage changes made during the deployment process.

## Tasks

- [x] Add a regions section in the issue templates
- [x] Writing descriptions to add new tags for SaaS deployments to make them easier to manage
- [x] Add a new tag `Update SaaS Properties`
